mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("polls.urls"))
]

mysite/polls/urls.py
from django.urls import path
from . import views
from polls.DataConversions import AenC as Sales
from polls.DataConversions import AdventureWorks as AdventureWorks
from polls.DataConversions import BikeStore as Bike
from polls.DataConversions import RandomForest as RandomForest
from polls.DataConversions import Clustering as Clustering
from polls.DataConversions import updateScript as Update
from polls.DataConversions import Regression as Reg
from polls.DataConversions import FrequentItem as FItem

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/statistieken", views.vote, name="statistieken"),
    ##region
    path('getSalesAmountPerRegion/', Sales.get_sales_amount_per_region, name='getSalesAmountPerRegion'),
    path('getSalesPerRegion/', Sales.get_sales_per_region, name='getSalesPerRegion'),
    path('getRegions/', Sales.get_regions, name='getRegions'),
    path('getYears/', Sales.get_years, name='getYears'),
    path('getSalesPerRegionPerMonth/<str:region>/<int:year>/', Sales.get_sales_per_region_per_month, name='getSalesPerRegionPerMonth'),
    path('getBestSoldProductInProductCategory/', Sales.get_best_sold_product_in_product_category, name='getBestSoldProductInProductCategory'),
    path('getDepartments/', Sales.get_Departmens, name='getDepartments'),
    path('getSalaryPerEmployeePerDepartment/<str:department>/', Sales.get_Salary_Per_Employee_Per_Department, name='getSalaryPerEmployeePerDepartment'),
    path('perform_regression/', Reg.perform_regression, name='perform_regression'),
    path('perform_frequentitemset/', FItem.perform_frequentitemset, name='perform_frequentitemset'),


    ##klant
    path('getAgeGroups/', Bike.get_age_groups, name='getAgeGroups'),
    path('getproductpercustomergroup/<str:age_group>/', Bike.get_product_per_customergroup, name='get_product_per_customergroup'),
    path('getmostprofitpercustomergroup/', Bike.get_most_profit_per_customergroup, name='get_most_profit_per_customergroup'),
    path('getBestSoldProductInProductCategoryBike/', Bike.get_best_sold_product_in_product_category, name='getBestSoldProductInProductCategoryBike'),
    ##supplier
    path('getQtySoldProductsPerSupplier/', AdventureWorks.get_qty_sold_products_per_supplier, name='getQtySoldProductsPerSupplier'),
    path('getAmountMoneyPerSupplier/', AdventureWorks.get_amount_money_per_supplier, name='getAmountMoneyPerSupplier'),
    path('getMostSoldProducts/', AdventureWorks.get_most_sold_products, name='getMostSoldProducts'),    
    ##machine learning
    path('predict_bonus/', RandomForest.predict_bonus, name='predict_bonus'),
    path('cluster/', Clustering.get_cluster, name='cluster'),
    
    path('getBestSoldProductInProductCategoryAdventure/', AdventureWorks.get_best_sold_product_in_product_category, name='getBestSoldProductInProductCategoryAdventure'),
    ##update
    path('update/', Update.Update_All_Final_Tables, name='update'),
]

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
import pandas as pd
from .models import Choice, Question

pagina = "leeg"


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
        if question_id == 1:
            pagina = "polls/detailRegio.html"
            print("You chose option 1.")
        elif question_id == 2:
            pagina = "polls/detailKlanten.html"
            print("You chose option 2.")
        elif question_id == 5:
            pagina = "polls/detailLeveranciers.html"
            print("You chose option 5.")
        elif question_id == 3:
            pagina = "polls/DetailProducten.html"
            print("You chose option 3.")
        elif question_id == 4:
            pagina = "polls/DetailMedewerkers.html"
            print("You chose option 4.")
        else:
            print("Invalid option.")
            pagina = "polls/detail.html"
 
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST["choice"])
        except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
            return render(
                request,
                pagina,
                {
                    "question": question,
                    "error_message": "You didn't select a choice.",
                },
            )
        else:
            selected_choice.votes += 1
            selected_choice.save()
            
            return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

class dashboards():
    def regio(request):
        sales_order = pd.read_csv('sales_order.csv')
        sales_order_item = pd.read_csv('sales_order_item.csv')
        product = pd.read_csv('product.csv')
        
        merged_data = pd.merge(sales_order_item, product, left_on='prod_id', right_on='id')
        merged_data = pd.merge(merged_data, sales_order[['id', 'region']], left_on='id_x', right_on='id')
        sales_per_region = merged_data.groupby('region')['id'].count().reset_index()
        sales_per_region.rename(columns={'id': 'total_product_sales'}, inplace=True)
        
        amount_per_region = merged_data.groupby('region')['unit_price'].sum().reset_index()
        amount_per_region.rename(columns={'unit_price': 'total_sales_amount'}, inplace=True)
        

mysite/polls/templates/polls/DetailMedewerkers.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<head>
    <title>Medewerker data</title>
    <h1>Medewerker data</h1>
    <a href="/" id="Home button" onmouseover="this.style.color='#A9A9A9'" onmouseleave="this.style.color='#FFFFFF'" style="background-color: gray;">Home</a>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>


<body>
    <div>
        <div class="row">
            <div class="column1" style="display: inline-block; width: 100%;">
                <label for="department" style="color: white;">Afdeling:</label>
                <select name="department" id="department1" onchange="fetchDepartment()"></select>
            </div>
            <div class="column1" style="display: inline-block; width: 100%;">
                <div id="sales-bar-chart"></div>
            </div>
        </div>
    </div>

    <div>
        <div id="results">
            <h2>Regression Results</h2>
            <p id="mse">Mean Squared Error: </p>
            <p id="r2">R-squared Score: </p>
            <div id="plot"></div>
        </div>
    </div>
</body>

</html>
    <script>
        updateCharts();
        setInterval(updateCharts, 300000);

        function updateCharts() {
            fetch('/perform_regression')
            .then(response => response.json())
            .then(data => {
                var mse = data.mse;
                var r2 = data.r2;

                var mseElement = document.getElementById("mse");
                var r2Element = document.getElementById("r2");
                // var graphElement = document.getElementById("plot");

                mseElement.innerHTML += mse;
                r2Element.innerHTML += r2;

                var graphData = [data.graphData, data.regressionLine];
                var layout = {
                    title: {
                        text: 'Regression Analysis',
                        font: {
                            color: '#ffffff'
                        }
                    },
                    plot_bgcolor: '#212121',
                    paper_bgcolor: '#212121',
                    xaxis: {
                        title: 'Salary',
                        color: '#ffffff',
                        tickfont: {
                            color: '#ffffff'
                        }
                    },
                    yaxis: {
                        title: 'Total Sales Amount',
                        color: '#ffffff',
                        tickfont: {
                            color: '#ffffff'
                        }
                    }
                };
                var config = { responsive: true };

                Plotly.newPlot('plot', graphData, layout, config);
            })
            .catch(error => {
                console.error(error);
            });
            fetch('/getDepartments')
                .then(response => response.json())
                .then(data => {
                    var departments = data.departments;
                    var select = document.getElementById("department1");
                    for (var i = 0; i < departments.length; i++) {
                        var opt = departments[i];
                        var el = document.createElement("option");
                        el.textContent = opt;
                        el.value = opt;
                        select.appendChild(el);
                    }
                    fetchDepartment();
                });
        }

        function fetchDepartment() {
            var department = document.getElementById("department1").value;
            if (department && department != 'R & D') {
                fetchSalarisPerMedewerkerPerDepartment(department);
            } else if (department && department == 'R & D') {
                fetchSalarisPerMedewerkerPerDepartment('R%20&%20D');
            }
        }

        function fetchSalarisPerMedewerkerPerDepartment(department) {
            fetch(`/getSalaryPerEmployeePerDepartment/${department}/`)
                .then(response => response.json())
                .then(data => {
                    var salaris_per_medewerker_per_department = data.salary_per_employee_per_department;

                    if (salaris_per_medewerker_per_department && salaris_per_medewerker_per_department.length > 0) {
                        var xValues = salaris_per_medewerker_per_department.map(item => `${item.emp_fname}  ${item.emp_lname}`);
                        var yValues = salaris_per_medewerker_per_department.map(item => item.salary);

                        Plotly.newPlot('sales-bar-chart', [{
                            x: xValues,
                            y: yValues,
                            type: 'bar',
                            marker: {
                                color: '#e377c2'
                            },
                        }], {
                            title: {
                                text: 'Salaris per medewerker per department',
                                font: {
                                    color: '#ffffff'
                                }
                            },
                            plot_bgcolor: '#212121',
                            paper_bgcolor: '#212121',
                            yaxis: {
                                title: 'Salaris',
                                color: '#ffffff',
                                tickfont: {
                                    color: '#ffffff'
                                }
                            },
                            xaxis: {
                                title: 'Medewerker',
                                color: '#ffffff',
                                tickfont: {
                                    color: '#ffffff'
                                },
                            }
                        });
                    } else {
                        document.getElementById("sales-bar-chart5").innerHTML = "Er zijn geen medewerkers gevonden voor dit department.";
                    }
                })
                .catch(error => {
                    console.error(error);
                });
        }
    </script>
</body>

</html>

mysite/polls/templates/polls/DetailProducten.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<head>
    <title>Product data</title>
    <h1>Product data</h1>
    <a href="/" id="Home button" onmouseover="this.style.color='#A9A9A9'" onmouseleave="this.style.color='#FFFFFF'" style="background-color: gray;">Home</a>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>


<body>
    <div>
        <div class="row">
            <div class="column1" style="display: inline-block; width: 49%;">
            </div>
        </div>
        <h2 class="white">machine learing</h2>
        <p class="white">Decision Tree:</p>
        <div id="sales-bar-chart"></div>
        <p id="accuracy" class="white"></p>
        <p class="white">K-Means Clustering:</p>
        <div id="clustering-chart"></div>
        <div id="sales-bar-chart2" style="display: inline-block; width: 49%;"></div>
        <div id="sales-bar-chart3" style="display: inline-block; width: 49%;"></div>
        <div id="sales-bar-chart4" style="display: inline-block; width: 49%;"></div>
        <div id="sales-bar-chart5" style="display: inline-block; width: 49%;"></div>
    </div>
    <script>
        updateCharts();

        setInterval(updateCharts, 300000);

        function updateCharts() {
            fetch('/predict_bonus', {
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
                .then(response => response.json())
                .then(data => {
                    var accuracy = document.getElementById("accuracy");
                    var output = document.getElementById("output");
                    accuracy.innerHTML = "Accuracy: " + data.accuracy;

                    var ageGroups = data.Age_Group.map(function (ageGroup) {
                        if (ageGroup === 0) {
                            return "<25";
                        } else if (ageGroup === 1) {
                            return "25-34";
                        } else if (ageGroup === 2) {
                            return "35-64";
                        } else if (ageGroup === 3) {
                            return "64+";
                        } else {
                            return "Unknown";
                        }
                    });

                    var predictedProfits = data.Average_Profit;

                    console.log(data.accuracy);
                    console.log(ageGroups);
                    console.log(predictedProfits);

                    var plotData = [{
                        x: ageGroups,
                        y: predictedProfits,
                        type: 'bar',
                        marker: {
                            color: '#e377c2'
                        }
                    }];

                    var layout = {
                        plot_bgcolor: '#212121',
                        paper_bgcolor: '#212121',
                        font: {
                            color: 'white'
                        },
                        xaxis: {
                            title: 'Age Group'
                        },
                        yaxis: {
                            title: 'Average Profit'
                        }
                    };

                    output = Plotly.newPlot('sales-bar-chart', plotData, layout);
                })
                .catch(error => {
                    console.error(error); a
                });

            fetch('/cluster')
                .then(response => response.json())
                .then(data => {
                    var labels = data.labels;
                    var centers = data.centers;
                    var dataPoints = data.dataPoints;
                    console.log(data);
                    console.log(dataPoints);

                    var xData = dataPoints.map(item => item.month);
                    var yData = dataPoints.map(item => item.Region);

                    var trace = {
                        x: xData,
                        y: yData,
                        mode: 'markers',
                        marker: {
                            color: labels,
                            size: 10,
                            colorscale: 'Viridis',
                            line: {
                                color: 'black',
                                width: 0.5
                            }
                        },
                        type: 'scatter'
                    };

                    var layout = {
                        title: {
                            text: 'K-Means Clustering',
                            font: {
                                color: '#ffffff'
                            }
                        },
                        plot_bgcolor: '#212121',
                        paper_bgcolor: '#212121',
                        xaxis: {
                            title: 'Maand',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            }
                        },
                        yaxis: {
                            title: 'Region',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            }
                        }
                    };

                    Plotly.newPlot('clustering-chart', [trace], layout);
                })
                .catch(error => {
                    console.error(error);
                });

            fetch('/getBestSoldProductInProductCategory')
                .then(response => response.json())
                .then(data => {
                    var best_sold_product_in_product_category = data.best_sold_product_in_product_category;
                    Plotly.newPlot('sales-bar-chart2', [{
                        x: best_sold_product_in_product_category.map(item => `${item.Category} - ${item.name}`),
                        y: best_sold_product_in_product_category.map(item => item.total_product_sales),
                        type: 'bar',
                        marker: {
                            color: '#e377c2'
                        },
                        title: 'AenC best verkochte producten per product categorie',
                    }], {
                        title: {
                            text: 'AenC best verkochte producten per product categorie',
                            font: {
                                color: '#ffffff'
                            }
                        },
                        plot_bgcolor: '#212121',
                        paper_bgcolor: '#212121',
                        yaxis: {
                            title: 'Hoeveelheid verkochte producten',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            }
                        },
                        xaxis: {
                            title: 'Product categorie',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            },
                        }
                    });
                })
                .catch(error => {
                    console.error(error);
                });

            fetch('/getBestSoldProductInProductCategoryBike')
                .then(response => response.json())
                .then(data => {
                    var best_sold_product_in_product_category = data.best_sold_product_in_product_category;
                    Plotly.newPlot('sales-bar-chart3', [{
                        x: best_sold_product_in_product_category.map(item => `${item.Sub_Category} - ${item.Product}`),
                        y: best_sold_product_in_product_category.map(item => item.Order_Quantity),
                        type: 'bar',
                        marker: {
                            color: '#e377c2'
                        },
                        title: 'BikeStore best verkochte producten per product categorie',
                    }], {
                        title: {
                            text: 'BikeStore best verkochte producten per product categorie',
                            font: {
                                color: '#ffffff'
                            }
                        },
                        plot_bgcolor: '#212121',
                        paper_bgcolor: '#212121',
                        yaxis: {
                            title: 'Hoeveelheid verkochte producten',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            }
                        },
                        xaxis: {
                            title: 'Product categorie',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            },
                        }
                    });
                })
                .catch(error => {
                    console.error(error);
                });

            fetch('/getMostSoldProducts')
                .then(response => response.json())
                .then(data => {
                    var most_sold_products = data.most_sold_products;
                    Plotly.newPlot('sales-bar-chart4', [{
                        x: most_sold_products.map(item => item.Name),
                        y: most_sold_products.map(item => item.total_sales_quantity),
                        type: 'bar',
                        marker: {
                            color: '#e377c2'
                        },
                        title: 'AdventureWorks best verkochte producten per product categorie',
                    }], {
                        title: {
                            text: 'AdventureWorks best verkochte producten per product categorie',
                            font: {
                                color: '#ffffff'
                            }
                        },
                        plot_bgcolor: '#212121',
                        paper_bgcolor: '#212121',
                        yaxis: {
                            title: 'Hoeveelheid verkochte producten',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            }
                        },
                        xaxis: {
                            title: 'Product categorie',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            },
                        }
                    });
                })
                .catch(error => {
                    console.error(error);
                });

            fetch('/getBestSoldProductInProductCategoryAdventure')
                .then(response => response.json())
                .then(data => {
                    var best_sold_product_in_product_category = data.most_sold_products_per_product_category;
                    Plotly.newPlot('sales-bar-chart5', [{
                        x: best_sold_product_in_product_category.map(item => item.CategoryName),
                        y: best_sold_product_in_product_category.map(item => item.total_sales_quantity),
                        type: 'bar',
                        marker: {
                            color: '#e377c2'
                        },
                        title: 'Northwind best verkochte producten per product categorie',
                    }], {
                        title: {
                            text: 'Northwind best verkochte producten per product categorie',
                            font: {
                                color: '#ffffff'
                            }
                        },
                        plot_bgcolor: '#212121',
                        paper_bgcolor: '#212121',
                        yaxis: {
                            title: 'Hoeveelheid verkochte producten',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            }
                        },
                        xaxis: {
                            title: 'Product categorie',
                            color: '#ffffff',
                            tickfont: {
                                color: '#ffffff'
                            },
                        }
                    });
                })

        }

    </script>
    <style>
        .white {
            color: rgb(245, 245, 245);
        }
    </style>
</body>

</html>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<div class="btn-group">
    {% if latest_question_list %}
    <ul>
        <img src="../../static/images/logoImglight.png" alt="logo" class="logo">
        {% for question in latest_question_list %}
        <a href="{% url 'polls:detail' question.id %}statistieken" class="">{{ question.question_text }}</a>
        {% endfor %}
    </ul>
    {% else %}
    <p>No statistics are available.</p>
    {% endif %}
</div>
<button id="update">update database</button>
<script>
    document.getElementById("update").addEventListener("click", function () {
        fetch('/update/')
            .then(response => {
                if (response.ok) {
                    document.getElementById("update").innerHTML = "Database Updated";
                } else {
                    console.error('Error updating database');
                }
            })
            .catch(error => {
                console.error('Error updating database:', error);
            });
    });
</script>

mysite/polls/templates/polls/loadingPage.html
<!DOCTYPE html>
<html>
<!-- {% load static %} -->
<body><img src="../../static/images/loadingIcon2.gif"><img></body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>